namespace TikTokAPI.Domain.Models.TikTok;

public enum ErrorCodeEnum
{
    OK,
    SPAM_RISK_TOO_MANY_POSTS,
    SPAM_RISK_USER_BANNED_FROM_POSTING,
    REACHED_ACTIVE_USER_CAP,
    UNAUDITED_CLIENT_CAN_ONLY_POST_TO_PRIVATE_ACCOUNTS,
    ACCESS_TOKEN_INVALID,
    SCOPE_NOT_AUTHORIZED,
    RATE_LIMIT_EXCEEDED,
    EMPTY,
    NO_CODE
}
